[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:226 Starting new HTTP connection (1): 192.168.8.136:8000
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:433 http://192.168.8.136:8000 "POST /api/v1/users HTTP/1.1" 500 118
[32mINFO    [0m root:Log.py:74 [INFO 2020-11-11 15:41:36]statusCode right, expected_code is 500, statusCode is 500